### ISSUE TITLE
test for long input

### ISSUE THREAD

**Issue by jjkennedy3** [jjkennedy3/TestRepo#21]
So I should be able to
break this line in the "raw" text box but it be rendered on one line in the output.

`So I should be able to
break this line in the "raw" text box but it be rendered on one line in the output.`

**Comment by jjkennedy3** [comment]
So I should be able to
break this line in the "raw" text box but it be rendered on one line in the output.

`So I should be able to
break this line in the "raw" text box but it be rendered on one line in the output.`

**Comment by jjkennedy3** [comment]
create a new comment

**Comment by jjkenn-1** [comment]
"author": [{
  "author": [{
    "@type": "Person",
    "name": "Daniel Carvalho",
    "description": "Repórter de política na Sucursal de Brasília desde 2016. Atualmente na cobertura do Palácio do Planalto, já cobriu o Congresso. Formado em jornalismo pela Universidade Católica de Pernambuco.",
    "image": "",
        "sameAs": ["https://www1.folha.uol.com.br/autores/daniel-carvalho.shtml","https://www.twitter.com/danielcarvalho_","https://www.instagram.com/danielcarvalhobsb/"],
        "workLocation": {
      "@type": "Place",
      "name": "Brasília"
    }
  },{
    "@type": "Person",
    "name": "Gustavo Uribe",
    "description": "É repórter da Folha desde 2014, com passagens pelas editorias de Poder e Cotidiano. Atua desde 2015 como setorista da Presidência da República.",
    "image": "",
        "sameAs": ["https://www1.folha.uol.com.br/autores/gustavo-uribe.shtml"],
        "workLocation": {
      "@type": "Place",
      "name": "Brasília"
    }
  },{
    "@type": "Person",
    "name": "Natália Cancian",
    "description": "Repórter com foco em saúde e políticas públicas. Na Folha desde 2010, trabalhou em Cotidiano e na Agência Folha, em São Paulo. É formada em jornalismo pela Universidade Estadual de Ponta Grossa, no Paraná.",
    "image": "",
        "sameAs": ["https://www1.folha.uol.com.br/autores/natalia-cancian.shtml","https://www.twitter.com/naticancian"],
        "workLocation": {
      "@type": "Place",
      "name": "Brasília"
    }
  }],
